# render.yaml
services:
  - type: web
    name: vev-squizer-backend
    runtime: python
    plan: free
    autoDeploy: true
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app
    pythonVersion: 3.11.9